#!/bin/sh
# [Gedit Tool]
# Input=nothing
# Save-files=nothing
# Name=[tool] search for selection
# Applicability=all
# Output=output-panel


#Language: Any
#Requires: Zenity
#Recommends: Git, RVM
#Menu Name: Grep on project
#Description: Executes grep of given string (selection by default) inside document dir. If it's inside a Git project, then it searches inside base repo dir. It Also looks for RVM, and if it is found, then it also searches inside the active gemset dir. Last version here.

#Applicability: all
#Output: output-panel
#Input: selection

read SELECTION

# allow to refine expression
EXPRESSION=$(zenity --entry --text='Expression to grep' --entry-text="$SELECTION")

# add document dir
GREP_PATHS=$GEDIT_CURRENT_DOCUMENT_DIR

# try to replace with git project dir
PROJ_DIR=$(git rev-parse --show-toplevel 2> /dev/null)
if [ ! '' = "$PROJ_DIR" ]; then
GREP_PATHS="$PROJ_DIR"
fi

# try to load gemset and add gemset dir
source $HOME/.rvm/scripts/rvm &> /dev/null
cd $GEDIT_CURRENT_DOCUMENT_DIR &> /dev/null
GEMSET_DIR=$(gem env gemdir)
if [ ! '' = "$GEMSET_DIR" ]; then
GREP_PATHS="$GREP_PATHS $GEMSET_DIR"
fi

# some annoying output (to be customized...)
EXCLUDES="--exclude-dir=.git --exclude=Makefile --exclude=*~"

# clean output for gedit to be able to open file:line references
SED_CLEAN="sed 's/\(.*:[0-9]\+:\)\(.*\)/\1 \2/'"

GREP_COMMAND="grep -RnwI $EXCLUDES '$EXPRESSION' $GREP_PATHS | $SED_CLEAN "

bash -l -c "$GREP_COMMAND"

echo
echo "--- Searched for '$EXPRESSION' inside:"
echo $GREP_PATHS
